name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python
        run: choco install python
      - name: Install Gauge
        run: choco install gauge
      - name: Python version
        run: python --version
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: PowerShell script
        uses: Amadevus/pwsh-script@v2.0.1
        with:
          script:
            gauge -v
            gauge install html-report
            gauge install xml-report
            gauge install java
            gauge run specs/
      - name: create-report
        uses: michaelhenry/create-report@v2.0.0
        with:
          title: Regression Report
          
