name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Azure PowerShell Action
        uses: Azure/powershell@v1
        with:
          inlineScript: Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
          azPSVersion: continue
          githubToken: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10.5'
      - name: Install Gauge
        run: |
          npm install -g @getgauge/cli
          choco install --no-progress --confirm gauge --force
      - uses: getgauge/setup-gauge@master
        with:
          gauge-version: '1.4.3'
          gauge-plugins: python, html-report, json-report, screenshot, spectacle, xml-report
      - name: Python version
        run: python --version
      - name: Gauge version
        run: gauge --version
      - name: Install requirements
        run: pip install -r requirements.txt	
      - name: Run Tests   
        run: C:\"Program Files"\gauge\bin\gauge.exe run .\demo\features\specs\rest_api.spec
