name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Azure PowerShell Action
        uses: Azure/powershell@v1
        with:
          inlineScript: Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
          githubToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Install Python
        run: choco install --no-progress --confirm python --version=3.10.0 --force
      - name: Install Gauge
        run: |
          npm install -g @getgauge/cli
          choco install --no-progress --confirm gauge --force
      - name: Python version
        run: python --version
      - name: Install requirements
        run: pip install -r requirements.txt	
      - name: Install reports
        run: gauge install xml-report
      - name: Run Tests   
        run: gauge run specs
